### ISSUE TITLE
Erreur: « ULLONG_MAX » n'a pas été déclaré dans cette portée

### ISSUE THREAD

**Issue by rchastain** [Carbecq/Zangdar_0#1]
Hello.

Pour votre information, j'ai une erreur de compilation, sous Linux, avec la version 0.37 (heureusement facilement réglée en suivant les informations données par le compilateur) : 

```
[roland@localhost src]$ g++ --version
g++ (Mageia 10.3.0-2.mga8) 10.3.0
[roland@localhost src]$ g++ -o ../zangdar *.cpp
Zobrist.cpp: Dans le constructeur « Zobrist::Zobrist() »:
Zobrist.cpp:19:51: erreur: « ULLONG_MAX » n'a pas été déclaré dans cette portée
   19 |     std::uniform_int_distribution<U64> dist(ZERO, ULLONG_MAX);
      |                                                   ^~~~~~~~~~
Zobrist.cpp:7:1: note: « ULLONG_MAX » is defined in header « <climits> »; did you forget to « #include <climits> »?
    6 | #include "ChessBoard.h"
  +++ |+#include <climits>
    7 | #include "Zobrist.h"
```
Une fois ajoutée la ligne suggérée, plus d'erreur.

Bonne continuation.

**Comment by Carbecq** [comment]
Bonjour,



Je travaille sous Windows 10, avec QtCreator. Et le programme se compile sans soucis.

J'ai ajouté l'include de climits, ça ne mange pas de pain.

Pour le Makefile, je n'en ai pas, c'est QtCreator qui s'occupe de tout.

Mais bon, il n'y a pas grand chose à y mettre )

Je viens de penser qu'il faut mettre une option pour désactiver les assert en mode release.

Peut -être aussi -O3 et -march pour avoir (un peu) plus de perf.

Et les noms de fichiers, ma foi, je préfère me consacrer à ce qu'il y a dedans.

En ce moment, je fais des pas mal d'essais avec de nouvelles idées que je pèche sur le forum CCC.

Enfin nouvelles pour moi, car tout ça est connu depuis longtemps.



Cordialement



Philippe






De : Roland Chastain ***@***.***>
À : Carbecq/Zangdar ***@***.***>
Sujet : [Carbecq/Zangdar] Zobrist.cpp:19:51: erreur: « ULLONG MAX » n'a pas été déclaré dans cette portée (Issue #1)
Date : 04/02/2022 17:09:55 Europe/Paris
Copie à : Subscribed ***@***.***>


Hello.
Pour votre information, j'ai une erreur de compilation, sous Linux, avec la version 0.37 (heureusement facilement réglée en suivant les informations données par le compilateur) :
***@***.*** src]$ g++ --version
g++ (Mageia 10.3.0-2.mga8) 10.3.0
***@***.*** src]$ g++ -o ../zangdar *.cpp
Zobrist.cpp: Dans le constructeur « Zobrist::Zobrist() »:
Zobrist.cpp:19:51: erreur: « ULLONG_MAX » n'a pas été déclaré dans cette portée
   19 |     std::uniform_int_distribution<U64> dist(ZERO, ULLONG_MAX);
      |                                                   ^~~~~~~~~~
Zobrist.cpp:7:1: note: « ULLONG_MAX » is defined in header « <climits> »; did you forget to « #include <climits> »?
    6 | #include "ChessBoard.h"
  +++ |+#include <climits>
    7 | #include "Zobrist.h"

Une fois ajoutée la ligne suggérée, plus d'erreur.

Par ailleurs, ça pourrait être bien d'inclure un Makefile, non ?

Et sinon, une remarque purement esthétique : le mélange de noms de fichiers avec majuscule et sans majuscule, ça ne fait pas joli. :)

Bonne continuation.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rchastain** [comment]
Merci pour ces informations. Bonne continuation.
