### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by SzotsGabor** [Carbecq/Zangdar_0#2]
Hi Philippe,

As you do not provide executables I tried to compile it myself but I ran into this type of problem:

In file included from Board.h:5,
                 from add_moves.cpp:1:
bitboard.h: In function 'constexpr int next_square(Bitboard&)':
bitboard.h:38:23: error: 'countr_zero' is not a member of 'std'
   38 |     auto index = std::countr_zero(b);

What shall I do?

Gabor Szots
CCRL testing group

**Comment by SzotsGabor** [comment]
I included -std=c++20 in the command line and the above error disappeared but there are new ones such as:

PolyBook.cpp: In member function 'void PolyBook::init(const std::string&)':
PolyBook.cpp:124:32: error: 'HOME' was not declared in this scope
  124 |     std::string     str_home = HOME;

And:

test_tactics.cpp:50:12: error: 'class Search' has no member named 'new_game'
   50 |     search.new_game();

**Comment by Carbecq** [comment]
Hi,
Thanks for the comments.
I made a new release today, and added a Makefile, along with some notes about the compilation.

- HOME must be specified in the Makefile. It is used to specify some locations I use to test the program. Unless you want to do some test, its value has no importance.
- test_tactics.cpp is not part of the source anymore. I made a first version of the release yesterday, then I noticed I have some files from a previous release. Im sorry for the inconvenience.

**Comment by SzotsGabor** [comment]
Using the makefile I get this message:

Access denied - SRC
File not found - -NAME
c:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib/libmingw32.a(lib64_libmingw32_a-crtexewin.o): in function `main':
C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexewin.c:70: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:44: Zangdar] Error 1

BTW, I can't see why I need to access your computer to be able to compile the source. Why are those parts not included in the distribution?

**Comment by Carbecq** [comment]
Hi,

Well, Im very sorry of all theses problems. 
I made a new release (2.14.05). I removed the variable HOME in the makefile. 
I also put 2 new binaries that don't use this variable.
Since this variable is only needed for me to locate some epd files, I didnt thought it was necessary to put them.
Do you think I should put them ?
Are you compiling on Windows or Linux ?
With Linux, I use the Makefile. With Windows, I use QtCreator.

**Comment by SzotsGabor** [comment]
I am on Windows 11.

I get almost the same error message using the makefile:

Access denied - SRC
File not found - -NAME
c:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: c:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib\libmingw32.a(lib64_libmingw32_a-crtexewin.o): in function `main':
C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexewin.c:70: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:47: Zangdar_rel] Error 1

But I also have good news. Compiling was successful using the following command line:

g++ *.cpp -std=c++20 -flto -O3 -march=native -pipe -DNDEBUG -fwhole-program -oZangdar_2.14.05-x64-SzG.exe

I got lots of warnings but the exe was created. Only, it does not move. Your compile is OK.

**Comment by SzotsGabor** [comment]
This is what my compile displays.

id name Zangdar 2.14.05
id author Philippe Chevalier
option name Hash type spin default 128 min 1 max 1024
option name Clear Hash type button
option name Threads type spin default 1 min 1 max 32
option name OwnBook type check default false
option name BookPath type string default ./
uciok
e2e4
go
info mate -34998       pv
bestmove a1a11
Time           0 s

Arena reports an illegal move.

PS. I am not a programmer so I don't always know what I am doing.

**Comment by Carbecq** [comment]
Ok,
its some others things I didn't thought of. I will make some modifications in the source to avoid this. I use the same source for me, and for github. Its not a good thing. 

For compiling, you must use the following options :  
-DHASH -DTT_XOR  -DLMR -DNEW_EVAL
along with the optimisation options : 
-pipe -std=c++20 -O3 -flto -DNDEBUG -fwhole-program -march=native
and, depending of your computer : 
 -mpopcnt -msse -msse3

I will remove in the future, the first options (HASH, TT_XOR, LMR, NEW_EVAL) from the Makefile. They serve to have, or not, certains heuristics/features in Zangdar. Obviously, you want them all !

For the optimisation options, I think that You can take them all; but Im not an expert.

For the machine dependant options, I have an old computer, and can only use popcount. If you have a better computer, you can perhaps use something like bmi2, avx2. But I don't know exactly the name of these options.

I hope its ok.

**Comment by SzotsGabor** [comment]
Success!

I looked at the makefile and copied some parts of it to the command line. And this time the exe was created and works the same way as yours!
This is how I did it:
g++ *.cpp -pipe -std=c++20 -O3 -flto -DNDEBUG -fwhole-program -march=native -mpopcnt -msse -msse3 -pg -DHASH -DTT_XOR  -DLMR -DNEW_EVAL -oZangdar_2.14.05-x64-SzG.exe 2>ki

I have little knowledge of what those command line switches do but the main thing is that it works!

**Comment by SzotsGabor** [comment]
> For the machine dependant options, I have an old computer, and can only use popcount. If you have a better computer, you can perhaps use something like bmi2, avx2. But I don't know exactly the name of these options.

I have an Intel i7-12700K CPU. I guess -march=native does all the optimizations without having to use other command line switches.

Thank you for your help and patience!

PS. For whatever reason, your compile is faster than mine.

**Comment by Carbecq** [comment]
Great !
The option -pg is for profiling. So its normal that your code is slower !
I think that your computer is newer than mine, and should be faster.
I have to thank you for your remarks. It helped me to have a source usabled for anyone, and not only for me !

**Comment by Carbecq** [comment]
Hi,
New release (2.14.06), and hopefully latest.
I removed all options relatives to features in the makefile.
Tell me how fast is your version ?

**Comment by SzotsGabor** [comment]
> Hi, New release (2.14.06), and hopefully latest. I removed all options relatives to features in the makefile. Tell me how fast is your version ?

Hi,

Makefile still does not work (same as before).

My version is about 10 % faster than yours, it's about 5000-5500 knps while yours is 4500-5000 (depends on CPU load distribution).
I used this command (no -pg): g++ *.cpp -pipe -std=c++20 -O3 -flto -DNDEBUG -fwhole-program -march=native -DHASH -DTT_XOR  -DLMR -DNEW_EVAL -oZangdar_2.14.06-x64-SzG.exe

**Comment by Carbecq** [comment]
Hi,
You don't need the options 
-DHASH -DTT_XOR -DLMR -DNEW_EVAL
as I removed them from the makefile. They are now defined in the file define.h, but you don't need to touch them, unless you want to experiment.
Im not familiar with Makefile under Windows. But the main point is that you can compile it.

Im now trying to improve the timer, as at present, Zangdar can't play like : 40 moves in 15 minutes.
I always did games likes : all moves in 10 minutes.

**Comment by SzotsGabor** [comment]
> Im now trying to improve the timer, as at present, Zangdar can't play like : 40 moves in 15 minutes. I always did games likes : all moves in 10 minutes.

I use 2min base time + 1sec increment for the CCRL blitz list. I also use 1.5min+0.75s because my PC is faster than the CCRL reference machine.
